### ISSUE TITLE
nycmesh/slack goes to expired invite instead of slack.nycmesh.net

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#102]
nycmesh/slack goes to https://nycmesh.slack.com/ which shows an expired invite.

I couldn't figure out where the alias for /slack is

**Comment by zethussuen** [comment]
Seems like it's here: https://github.com/nycmeshnet/nycmesh.net/blob/master/static/_redirects

**Comment by OlivierMorf** [comment]
Solved.  The slack link need to periodically be updated.
