### ISSUE TITLE
Expand address fields in join form (don't send anyone to the wrong Madison Street / Water Street / etc.)

### ISSUE THREAD

**Issue by wizardishungry** [nycmeshnet/nycmesh.net#18]
from @woa100 https://github.com/nycmeshnet/nycmeshnet.github.io/issues/45
Expand "Address"
to

Street Address ____
Unit Number ____
Borough ____
Zip Code ____

(We had some confusion about which Madison Street an install was taking place at - both Madison Streets in New York are within the coverage zone!)

**Comment by LydonThorpe** [comment]
Old issue, issue solved with MeshDB. Closing issue.
