### ISSUE TITLE
Link to "help" page

### ISSUE THREAD

**Issue by woa100** [nycmeshnet/nycmesh.net#27]
@olivernyc

Could you add "Volunteer" to "Join" and "Donate" on the top banner and in the first block of text on the homepage? I think it should come second in the order - I'll leave the color up to you. (I'm not sure how to make a new class otherwise I'd make the edit myself.)

Perhaps the sentence in the first block of text should say, "**Volunteer** to help us maintain and grow our network."

**Comment by olivernyc** [comment]
https://github.com/nycmeshnet/nycmesh.net/pull/57
