### ISSUE TITLE
Supernodes don't say Supernode on the infobox

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#32]
Infobox for SN1 says "227", it should say "Supernode1"

I can see this info on rollover, but rollover isn't even available on mobile. Is there some nice way to get all of the "notes" info into the infobox?

**Comment by olivernyc** [comment]
Fixed in https://github.com/nycmeshnet/node-map/commit/ddb1ee3f2b90f315f6463dd0b297ed6bc637a66d
