### ISSUE TITLE
On the Join Page (edits)

### ISSUE THREAD

**Issue by OlivierMorf** [nycmeshnet/nycmesh.net#51]
On the join page. 
A/
On the first line, can we add "please include you node number"
=>  For progress on your node request, email support@nycmesh.net, please include your node number.

above the address filed, can we add "Complete"  or "(Complete)"
=> Street Address (Complete)
or 
= > Complete Street Address 
And in the filed add the Zip code
=> 285 Fulton Street, New York NY 10006, USA

and under the submit button 
=> (by clicking "submit request" you agree to have your node published on the map).

**Comment by LydonThorpe** [comment]
Old issue. All new join form changes should be done on MeshDB forms.
