### ISSUE TITLE
Pay button still visible after paying

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#70]
![paywithcardbutton](https://user-images.githubusercontent.com/1037006/55673360-2ebbfa80-5875-11e9-8754-c7742090feaf.png)

New members confused because "Pay with card" button doesn't go away after payment. Some members have paid twice because of this.

**Comment by olivernyc** [comment]
Fixed in https://github.com/nycmeshnet/nycmesh-stripe/commit/b273ccf89c9ea615efd71742746db7e8cfd46126
