### ISSUE TITLE
Can the map page be a bit wider. 

### ISSUE THREAD

**Issue by OlivierMorf** [nycmeshnet/nycmesh.net#71]
Can the map page be a bit wider. I think it's narrower than before (top-bottom)  make it difficult to work with.
![Screen Shot 2019-04-30 at 10 45 12 PM](https://user-images.githubusercontent.com/44938525/57004175-ceca2280-6b9a-11e9-9778-36393fe48e59.png)

**Comment by olivernyc** [comment]
Fixed in https://github.com/nycmeshnet/node-map/commit/ffd85bbe35c090dcc27ec4ade7319c3926f0d3aa
