### ISSUE TITLE
Stats are off by one

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#72]
The total on https://www.nycmesh.net/stats is always one less than the total on /map

<img width="514" alt="Screen Shot 2019-05-14 at 9 52 27 AM" src="https://user-images.githubusercontent.com/1037006/57703421-08386e80-762e-11e9-9a5e-448be2626c6a.png">

**Comment by olivernyc** [comment]
The issue was node 2919 installDate set to 6/3/2019. I changed it to 5/3/2019.

**Comment by olivernyc** [comment]
Also 3217 is missing an install date

**Comment by bhny** [comment]
still off by one :-(

**Comment by olivernyc** [comment]
Did you add an install date for 3217?

**Comment by bhny** [comment]
added date to 3217 and stats and map are the same total now
