### ISSUE TITLE
Need option to pay actual cost of install

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#74]
Installs are costing us about $240 so if someone can afford that we should encourage the option. Here's my rough proposal-

<img width="629" alt="Screen Shot 2019-06-17 at 3 23 25 PM" src="https://user-images.githubusercontent.com/1037006/59632062-4df9c280-9117-11e9-8291-1ac0afda5453.png">

**Comment by OlivierMorf** [comment]
I would have the $240 first, preselected, with option to choose the $110 on second position

**Comment by bhny** [comment]
I chose this as the least controversial option so we can do it straight away. Changing defaults requires some debate and changing a lot of other pages and outreach material.

**Comment by jedahan** [comment]
I'd recommend changing the punctuation to separate out the `$160 - 50` reading which feels like a range to me.
example:

> The NYC Mesh subsidized install costs $160. The installer receives $50 for their labour, and $110 helps cover some of the equipment. The total bill is due upon completion.
> 
> The full cost of equipment is $240, so if you can afford to, please select that option.

**Comment by apackin** [comment]
Since you're already including the costs in the radio dials I think you can cut out most of the description like:

## Thank you for installing a mesh node!

In addition to Parts and Equipment, NYC Mesh installation costs $50 paid to your installer directly.

---
Parts and Equipment
 - [x] $240 (Full cost of equipment)
 - [ ] $110 (Subsidized by donors)

**Please also subscribe me to a monthly donation**
 - [ ] $100 (business)
 - [ ] $50
 - [x] $20
 - [ ] I do not wish to continually support NYC Mesh
 
						 [Pay with Card]

**Comment by apackin** [comment]
Also wanted to flag that there are two similar pages that his thread could be referring to:
https://www.nycmesh.net/invoice
https://www.nycmesh.net/pay

Is one of those pages deprecated or do both of them need to be updated?

**Comment by olivernyc** [comment]
Those are both in use -- I think /invoice is used when we do installs at a business

**Comment by bhny** [comment]
yes invoice is for business and has url params to set the amount

**Comment by apackin** [comment]
Opened a pr for small changes to copy https://github.com/nycmeshnet/nycmesh.net/pull/78

I'd love to learn more about why there is a separate page for business/home installs. 
Does having the body text describing the payment breakdown add something to residential mesh members that business members don't need? Do business not pay the additional $50 labor fee separately or something?


It looks like you still have the code for using an `a` query param on the pay240 page as in  `https://www.nycmesh.net/pay240?a=500`, but it doesn't update the description text. Is the query param deprecated on that page or should it be used to update the description text as well as the Parts and Equipment amount?
