### ISSUE TITLE
Validate phone number

### ISSUE THREAD

**Issue by carlos-guzman** [nycmeshnet/nycmesh.net#91]
Add a Javascript check for the format of the phone number in https://github.com/nycmeshnet/nycmesh.net/blob/a4def79db8f49ee15efdbdc7286100bc734de8b7/layouts/partials/join.html 

See the ticket for node 4585, which has 11 digits

**Comment by LydonThorpe** [comment]
Old issue, new feedback should be opened as an issue for MeshDB forms.
