### ISSUE TITLE
Line of Sight tool seems to be broken.

### ISSUE THREAD

**Issue by abhishekpradhan** [nycmeshnet/nycmesh.net#99]
The line of sight tool under the "Resources" section at the bottom of the page seems to be broken. Until it's fixed I think the best mitigation is to remove that link.

**Comment by olivernyc** [comment]
What is broken? It seems to be working for me.

**Comment by abhishekpradhan** [comment]
I tried using it with multiple addresses in the Bed Stuy, Crown Heights, Downtown Brooklyn or FiDi, they all return no building information or no line of sight. This doesn't seem correct as when you look at the map I tried addresses that are clearly in the coverage area.

**Comment by bhny** [comment]
can you give us an example of an address you tried

**Comment by abhishekpradhan** [comment]
976 Fulton Street, Brooklyn, New York 11238
881 Fulton Street, Brooklyn, New York 11238
30 Macon Street, Brooklyn, New York 11216
12 Macon Street, Brooklyn, New York 11216
16 Downing Street, Brooklyn, New York 11238
110 Downing Street, Brooklyn, New York 11238

**Comment by olivernyc** [comment]
Thanks for the additional information. This missing building data is a known issue: https://github.com/meshcenter/mesh-api/issues/36

I know the reason for the issue (silly XML thing) and have a fix for it. Just haven't had the time lately. I'll see if I can do it tomorrow and will comment here when it is resolved.

**Comment by olivermesh** [comment]
FYI the fix is here: https://github.com/meshcenter/mesh-api/commit/1b075f048ecf54654dfb0480928072416a785bd7#diff-21b2263b8d4368c1fb7dd09abdc87651

I have to reimport the data. Giving it a shot now...

**Comment by olivermesh** [comment]
Reimport complete! 1,083,437 buildings now in the db, up from ~900k. It seems some of the buildings you posted are still not found, but I believe that is because they were constructed since 2014 so not included in the dataset.
